#!/usr/bin/env bash
set -eu

dir="$(cd "$(dirname "$0")/.." && pwd)"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

tmux list-keys >/dev/null

split_keys() {
  awk '{
    sub(/^bind-key +(-r +)?-T +[^ ]+ +/, "")
    key = $1
    cmd = $0
    sub(/^[^ ]+ +/, "", cmd)
    print key "\t" cmd
  }' "$1"
}

split_notes() {
  awk 'NF > 1 { key = $1; sub(/^[^ ]+ +/, ""); print key "\t" $0 }' "$1"
}

display() {
  printf '%s' "$1" | sed -E \
    -e "s|$HOME|~|g" \
    -e 's/\\n/ /g' \
    -e 's/\\t/ /g' \
    -e 's|run-shell "tmux (.*); [^;]*copycat_mode_quit\.sh; true"|\1|' \
    -e 's/\\+"/"/g' \
    -e 's/\\+;/;/g' \
    -e 's|~/\.config/tmux/plugins/[^ ]+/scripts/||g' \
    -e 's|~/\.config/tmux/plugins/[^ ]+/||g' \
    -e 's/  +/ /g' \
    -e 's/^ //' \
    -e 's/ $//'
}

describe() {
  local key="$1" action="$2"
  case "$action" in
    *select-pane*) ;;
    *) printf '%s' "$action"; return ;;
  esac
  case "$key" in
    C-h) printf 'move pane left (passes C-h to Neovim when open)' ;;
    C-j) printf 'move pane down (passes C-j to Neovim when open)' ;;
    C-k) printf 'move pane up (passes C-k to Neovim when open)' ;;
    C-l) printf 'move pane right (passes C-l to Neovim when open)' ;;
    C-\\\\) printf 'go to the last used pane' ;;
    *) printf '%s' "$action" ;;
  esac
}

missing_script() {
  local word path
  for word in $1; do
    path="${word%\"}"
    path="${path#\"}"
    case "$path" in
      *.sh) [ -e $path ] || return 0 ;;
    esac
  done
  return 1
}

unescape_key() {
  printf '%s' "$1" | sed -E -e 's/^"(.*)"$/\1/' -e 's/\\(.)/\1/g'
}

for table in root prefix copy-mode-vi; do
  tmux list-keys -T "$table" > "$work/live-$table.raw"
  tmux list-keys -N -T "$table" > "$work/notes-$table.raw"
  tmux -L tmux-shortcuts-defaults -f /dev/null start-server \; list-keys -T "$table" > "$work/default-$table.raw"

  split_keys "$work/live-$table.raw"    > "$work/live-$table.tsv"
  split_keys "$work/default-$table.raw" > "$work/default-$table.tsv"
  split_notes "$work/notes-$table.raw"  > "$work/notes-$table.tsv"

  awk -F'\t' -v notes="$work/notes-$table.tsv" -v defs="$work/default-$table.tsv" '
    FILENAME == notes { note[$1] = $2; next }
    FILENAME == defs  { def[$1 SUBSEP $2] = 1; next }
    {
      if ($1 ~ /Mouse|Wheel|DoubleClick|TripleClick/) next
      action = (($1 in note) && note[$1] != "") ? note[$1] : $2
      kind = (($1 SUBSEP $2) in def) ? "d" : "c"
      print kind "\t" $1 "\t" action "\t" $2
    }
  ' "$work/notes-$table.tsv" "$work/default-$table.tsv" "$work/live-$table.tsv" |
    LC_ALL=C sort -t "$(printf '\t')" -k2,2 > "$work/class-$table.tsv"
done

has_kind() {
  grep -q "$(printf '^%s\t' "$1")" "$2"
}

rows() {
  local kind="$1" file="$2" k key action raw suffix
  while IFS=$'\t' read -r k key action raw; do
    [ "$k" = "$kind" ] || continue
    suffix=""
    missing_script "$raw" && suffix=" (script missing)"
    action="$(display "$(describe "$key" "$action")")$suffix"
    case "$action" in
      *'`'*) printf -- '- `%s` — %s\n' "$(unescape_key "$key")" "$action" ;;
      *)     printf -- '- `%s` — `%s`\n' "$(unescape_key "$key")" "$action" ;;
    esac
  done < "$file"
}

prefix="$(tmux show-options -gv prefix)"
base_index="$(tmux show-options -gv base-index)"
pane_base_index="$(tmux show-options -gv pane-base-index)"
mouse="$(tmux show-options -gv mouse)"

{
  printf '# tmux shortcuts\n\n'
  printf 'Generated by `scripts/shortcuts.sh` on every config load; edit `tmux.conf`,\nnot this file.\n\n'
  printf 'Prefix is `%s` — `prefix X` means press `%s`, release, then `X`. Windows are\n' "$prefix" "$prefix"
  if [ "$mouse" = on ]; then
    printf 'numbered from %s, panes from %s. Mouse is on: click selects panes, drag a\n' "$base_index" "$pane_base_index"
    printf 'border to resize, the wheel scrolls and can enter copy mode, double-click\ncopies a word.\n\n'
  else
    printf 'numbered from %s, panes from %s. Mouse is off.\n\n' "$base_index" "$pane_base_index"
  fi
  printf '`prefix ?` lists every binding and `prefix k` opens a searchable popup of\nthe same; this file mirrors the live key tables.\n'

  for table in root prefix copy-mode-vi; do
    case "$table" in
      root) title="No prefix" ;;
      prefix) title="Prefix \`$prefix\`" ;;
      copy-mode-vi) title="Copy mode (vi)" ;;
    esac
    file="$work/class-$table.tsv"
    printf '\n## %s\n' "$title"
    if has_kind c "$file"; then
      printf '\n### Added or changed\n\n'
      rows c "$file"
    fi
    if has_kind d "$file"; then
      printf '\n### tmux defaults\n\n<details>\n<summary>Show defaults</summary>\n\n'
      rows d "$file"
      printf '\n</details>\n'
    fi
  done
} > "$work/SHORTCUTS.md"

mv "$work/SHORTCUTS.md" "$dir/SHORTCUTS.md"
